language: java
jdk: oraclejdk8
#install: true
#script: ./mvnw clean install
notifications:
    email:
        - shigger@gmail.com
before_install:
    - pip install --user codecov    #Install codecov
after_success:
    - codecov                       #Run codecov